os:
  - linux

language: go

go:
  - "1.10.x"

install: true

env:
  - VERSION=0.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "v$VERSION" --force
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file:
      - "build/example-osx-x64.tar.gz"
      - "build/example-osx-x32.tar.gz"
      - "build/example-linux-x64.tar.gz"
      - "build/example-linux-x32.tar.gz"
      - "build/example-linux-arm64.tar.gz"
      - "build/example-linux-arm7.tar.gz"
      - "build/example-linux-alpine.tar.gz"
    skip_cleanup: true

notifications:
  email: false

before_script:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/rendon/testcli
  - go get

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then /bin/bash -c ./.travis/build.sh; fi